#!/bin/bash

make main
cat "$1" | ./main > prog.out

EXIT_CODE="$?"

if [ "$EXIT_CODE" == "0" ]; then
    ./ic22int_2022-11-14 prog.out
    echo "Interpreter exit code: $?"
else
    echo "Compiler exited with errors, code: $EXIT_CODE"
fi
